steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  # Deploy to cloud function
  args: ['functions', 'deploy', 'wiki-waku-function', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--region', 'us-central1', '--entry-point', 'hello_pubsub', '--source', '.', '--memory', '128Mi', '--timeout', '60s', '--max-instances', '1' , '--gen2',]